// Generated by https://quicktype.io

export interface Cliente {
  id:                number;
  empresaId:         number;
  listaPrecioId:     null;
  usuarioCreacionId: null;
  fechaModif:        string;
  usuarioModif:      null;
  fechaCreacion:     string;
  razonSocial:       string;
  nroDocumento:      string;
  direccion:         string;
  telefono:          string;
  email:             string;
  excentoIva:        boolean;
  latitud:           string;
  longitud:          string;
  predeterminado:    boolean;
  empleado:          null;
  propietario:       boolean;
  activo:            boolean;
}
