// Generated by https://quicktype.io

import { Cliente } from "./clientes.interface";
import { Sucursal } from "./sucursal.interface";

export interface ReportCobranza {
  detalles: Detalle[];
  agrupado: Agrupado[];
}

export interface Agrupado {
  medioPago:        string;
  cantidadCobranza: number;
  importeTotal:     number;
}

export interface Detalle {
  fechaVenta:     string;
  id:             string;
  nroComprobante: string;
  importeTotal:   string;
  cobranzaId:     number;
  cliente:        Cliente;
  sucursal:       Sucursal;
  importeCobrado: string;
  nroRef:         null | string;
  medioPago:      string;
}

