// Generated by https://quicktype.io

import { Cliente } from "./clientes.interface";
import { Sucursal } from "./sucursal.interface";

export interface ReportCobranza {
  detalles: Detalle[];
  agrupado: Agrupado[];
}

export interface Agrupado {
  medioPago:        string;
  cantidadCobranza: number;
  importeTotal:     number;
}

export interface Detalle {
  fechaVenta:     string;
  id:             string;
  nroComprobante: string;
  importeTotal:   string;
  cobranzaId:     number;
  cliente:        Cliente;
  sucursal:       Sucursal;
  importeCobrado: string;
  nroRef:         null | string;
  medioPago:      string;
}


export interface ReporteSucursal {
  sucursalid:     number;
  sucursalnombre: string;
  totalventas:    string;
  totalimporte:   string;
}

export interface ReporteVariante {
  id:           string;
  coderp:       string;
  producto:     string;
  variedad:     string;
  presentacion: string;
  vendidos:     string;
  peso:         string;
  totalimporte: string;
}

export interface ReporteCliente {
  doc:           string;
  razonsocial:   string;
  totalimporte:  string;
  totalfacturas: string;
}

export interface ReporteMedioPago {
  id:                  string;
  mediopago:           string;
  totalimportecobrado: string;
  cantidad:            string;
}

export interface ReporteVendedor {
  id:       number;
  vendedor: string;
  cantidad: string;
  peso:     string;
  total:    string;
}
